"use client";

import type { FormEvent, ReactNode } from "react";
import { useState } from "react";
import { SectionIntro } from "@/components/section-intro";
import type { SiteCopy } from "@/components/site-types";

export function ContactSection({ content }: { content: SiteCopy["contact"] }) {
  const [isSent, setIsSent] = useState(false);
  function submitContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setIsSent(true); }
  return <section id="contact" className="border-t border-[#0b4f7e]/10 bg-white px-6 py-24 md:pl-20 md:pr-12 lg:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow={content.eyebrow} title={content.title} /><div className="mt-12 grid gap-14 lg:grid-cols-2 lg:gap-24"><form onSubmit={submitContact} className="space-y-6"><Field label={content.name}><input required name="name" type="text" /></Field><Field label={content.email}><input required name="email" type="email" /></Field><Field label={content.subject}><select name="subject">{content.subjects.map((subject) => <option key={subject}>{subject}</option>)}</select></Field><Field label={content.message}><textarea required name="message" rows={4} /></Field><button type="submit" className="relative isolate overflow-hidden bg-[#06395f] px-6 py-3.5 text-sm font-semibold text-white before:absolute before:inset-0 before:-z-10 before:origin-left before:scale-x-0 before:bg-[var(--secondary)] before:transition-transform before:duration-500 before:ease-[cubic-bezier(.22,1,.36,1)] before:content-[''] hover:before:scale-x-100 focus-visible:before:scale-x-100 motion-reduce:before:transition-none">{content.send}</button>{isSent && <p role="status" className="text-sm leading-6 text-[#0b4f7e]">{content.sent}</p>}</form><div className="border-t border-[#0b4f7e]/15 pt-9 lg:border-l lg:border-t-0 lg:pl-14 lg:pt-0"><h3 className="font-mono text-xs uppercase tracking-[0.14em] text-[#37627d]">{content.details}</h3><address className="mt-4 not-italic text-base leading-7 text-[#06395f]">IFCPA/CRTV<br />Ekounou, Yaoundé, Cameroun<br /><a href="tel:+237656700852" className="underline decoration-[#2ba9df] underline-offset-4">+237 6 56 70 08 52</a><br /><a href="mailto:ifcpa.crtv@gmail.com" className="underline decoration-[#2ba9df] underline-offset-4">ifcpa.crtv@gmail.com</a></address><div className="mt-10">{content.faq.map((item, index) => <details key={item.question} open={index === 0} className="border-t border-[#0b4f7e]/15 py-5"><summary className="cursor-pointer list-none pr-8 text-sm font-semibold text-[#06395f] marker:content-none">{item.question}<span className="float-right text-xl leading-4 text-[#2ba9df]">+</span></summary><p className="mt-3 text-sm leading-6 text-[#37627d]">{item.answer}</p></details>)}</div></div></div></div></section>;
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return <label className="block"><span className="font-mono text-[11px] uppercase tracking-[0.11em] text-[#37627d]">{label}</span><span className="mt-2 block [&_input]:w-full [&_input]:border-b [&_input]:border-[#0b4f7e]/25 [&_input]:bg-transparent [&_input]:px-0 [&_input]:py-3 [&_input]:text-[#06395f] [&_input]:outline-none [&_input:focus]:border-[#2ba9df] [&_select]:w-full [&_select]:border-b [&_select]:border-[#0b4f7e]/25 [&_select]:bg-transparent [&_select]:px-0 [&_select]:py-3 [&_select]:text-[#06395f] [&_select]:outline-none [&_select:focus]:border-[#2ba9df] [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:border-b [&_textarea]:border-[#0b4f7e]/25 [&_textarea]:bg-transparent [&_textarea]:px-0 [&_textarea]:py-3 [&_textarea]:text-[#06395f] [&_textarea]:outline-none [&_textarea:focus]:border-[#2ba9df]">{children}</span></label>;
}
